{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-backup-restore.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql-backup-restore.labels" . | nindent 4 }}
type: Opaque
data:
  aws_access_key_id: {{ toYaml .Values.secrets.aws_access_key_id | b64enc |  quote }}
  aws_secret_access_key: {{ toYaml .Values.secrets.aws_secret_access_key | b64enc |  quote }}
  postgresql_backup: {{ toYaml .Values.secrets.postgresql_backup | b64enc |  quote }}
  postgresql_restore: {{ toYaml .Values.secrets.postgresql_restore | b64enc |  quote }}
{{- end }}