apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bucket-backup-restore.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bucket-backup-restore.labels" . | nindent 4 }}
type: Opaque
data:
  aws_access_key_id: {{ toYaml .Values.secret.aws_access_key_id | b64enc |  quote }}
  aws_secret_access_key: {{ toYaml .Values.secret.aws_secret_access_key | b64enc |  quote }}
  rclone: |
    {{ .Values.secret.rclone | b64enc | indent 4 }}
